# -*- mode: ruby -*-
# vi: set ft=ruby :

#$add_insecure_registry = <<SCRIPT
#    service docker stop
#    sed -i 's/DOCKER_OPTS="-r=true ${DOCKER_OPTS}"/DOCKER_OPTS="--insecure-registry=192.168.0.16:5000 -r=true ${DOCKER_OPTS}"/' /etc/default/docker
#    service docker start
#SCRIPT

#$remove_registry_container = <<SCRIPT
#    echo "Stop docker-registry container..."
#    docker stop docker-registry > /dev/null 2>&1
#    echo "Remove docker-registry container..."
#    docker rm docker-registry
#SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 5000, host: 5000 # docker-registry port

  config.vm.network "private_network", ip: "192.168.0.16"
  
  # Exclude docker_registry vm from proxying
  config.proxy.no_proxy = "192.168.0.16"

#  config.vm.provision "shell", inline: $add_insecure_registry

#  config.vm.provision "shell", inline: $remove_registry_container

  config.vm.provision "docker" do |d|
#    d.run "docker-registry", image: "registry", args: "-p 5000:5000 -e STORAGE_PATH=/registry -v '/docker/registry:/registry'"
  end

  # Have Vagrant install docker for us...
  config.vm.provision "docker"

  # ...and then we configure it ourselves. Otherwise we'd have a chicken-egg situation with adding 
  # the --insecure-registry and running containers from our private registry.
  config.vm.provision "shell", path: "configure_docker.sh"

  # Setup the registry container
  config.vm.provision "shell", path: "setup_docker_registry.sh"


  config.vm.synced_folder "registry_store/", "/docker/registry"
	
  config.vm.provider "virtualbox" do |v|
    v.name = "docker_registry_vm"
    v.gui = true
  end
end
