# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 5000, host: 5000 # docker-registry port

  config.vm.network "private_network", ip: "192.168.0.16"
  
  config.vm.provision "docker" do |d|
    d.run "docker-registry", image: "registry", args: "-p 5000:5000 -e STORAGE_PATH=/registry -v '/docker/registry:/registry'"
  end
  config.vm.synced_folder "docker_registry/", "/docker/registry"
	
  config.vm.provider "virtualbox" do |v|
    v.name = "docker_registry_vm"
  end
end
