# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 5000, host: 5000 # docker-registry port
  #config.vm.network "forwarded_port", guest: 8080, host: 8080
  #config.vm.network "forwarded_port", guest: 8181, host: 8181

  #config.vm.provision "docker"
  #config.vm.provision :shell, path: "setup_env.sh"
  #config.vm.provision :shell, path: "run_glassfish.sh"
  
  config.vm.provision "docker" do |d|
    d.run "docker-registry", image: "registry", args: "-e STORAGE_PATH=/registry -v '/docker/registry:/registry'"
  end

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
  end
end
